# Crowdin configuration file
# see: https://support.crowdin.com/configuration-file/
#
# you will need the CLI client
# see: https://support.crowdin.com/cli-tool/

project_identifier: qownnotes
project_id: 158883
base_path: "."

# the api token has to be provided by ~/.crowdin.yaml
# generate a personal token on https://crowdin.com/settings#api-key
#api_token: XXXX

files:
  - # source files filter
    source: "/src-bex/_locales/en/messages.json"
    # where translations live
    translation: "/src-bex/_locales/%locale_with_underscore%/messages.json"
